### ISSUE TITLE
RealSense calibration with Kalibr

### ISSUE THREAD

**Issue by brian-h-wang** [MIT-SPARK/Kimera-VIO-ROS#73]
Hello - I'm working on getting Kimera running with a RealSense D435i, following the hardware setup instructions. I've run Kalibr calibration for the left and right cameras on the RealSense, and gotten a camchain.yaml file which I'll paste below.

I'm not sure how to convert this into the Kimera format (e.g. Kimera-VIO/params/RealSenseIR/LeftCameraParams.yaml and RightCameraParams.yaml). I've looked at config2kimeravio.py as suggested by the instructions, but this script seems to require an IMU calibration file as well.  Is it required to also calibrate the IMU using Kalibr, or is there something else I'm missing?

Thanks for your work releasing and supporting this code!
Brian

Here are the contents of the camchain.yaml file outputted by Kalibr:
```
cam0:
  cam_overlaps: [1]
  camera_model: pinhole
  distortion_coeffs: [0.3209965194308784, 0.8070591908434555, -2.9447705598973335,
    3.8238784975539826]
  distortion_model: equidistant
  intrinsics: [393.992543431021, 392.8544350474975, 319.018468455671, 243.3671252772004]
  resolution: [640, 480]
  rostopic: /camera/infra1/image_rect_raw
cam1:
  T_cn_cnm1:
  - [0.9999851461535377, 0.00023630422730915455, 0.005445331264508205, -0.048195085165018095]
  - [-0.00023563891196742644, 0.9999999646945043, -0.0001228221224057136, -1.470629712559274e-05]
  - [-0.00544536009564487, 0.00012153716609029549, 0.9999851665310473, -0.0005490088828873391]
  - [0.0, 0.0, 0.0, 1.0]
  cam_overlaps: [0]
  camera_model: pinhole
  distortion_coeffs: [0.46531388970311016, -1.2269602724399762, 7.172420924475765,
    -12.274713687690216]
  distortion_model: equidistant
  intrinsics: [392.55726805499006, 391.3853067072748, 317.03442389767497, 242.9937460456073]
  resolution: [640, 480]
  rostopic: /camera/infra2/image_rect_raw
```
